// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Customer struct {
	ID        int64            `json:"id"`
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type Order struct {
	ID         int64            `json:"id"`
	CustomerID int64            `json:"customer_id"`
	ProductID  int64            `json:"product_id"`
	Quantity   int32            `json:"quantity"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
}

type Product struct {
	ID    int64       `json:"id"`
	Code  string      `json:"code"`
	Price int32       `json:"price"`
	Stock int32       `json:"stock"`
	Color pgtype.Text `json:"color"`
}
